[Stable only] Fix CI jobs
This patch switches using f-strings instead of regular ones in places
where pep8 was complaining about with error C0209. That part is
cherry-picked from commit [1] in master branch.

This patch also removes lower-constraints job as we agreed some time ago
to not run that job in the stable branches.

It also removes functional and tempest jobs which runs OVS and
OVN from master/main branches. We don't need to test that in the stable
release. Those jobs should be run in the master branch and in stable
branches are not needed anymore.

Finally it also adds test_source_ip_port_{tcp,udp}_traffic tests to the
skiplist as those tests are very unstable now and requires more
investigation what's wrong there. This is "backport" of the patch [2].

[1] https://review.opendev.org/c/openstack/ovn-octavia-provider/+/816829
[2] https://review.opendev.org/c/openstack/ovn-octavia-provider/+/799864

Conflicts:
    lower-constraints.txt
    zuul.d/project.yaml

Change-Id: Id7d8422f07475aee58c2f283da67cc5e171f889b
(cherry picked from commit 071d3347b57d8a5a469fcf06acb1870c279b0c65)