[Stable only] Fix CI jobs
This patch switches using f-strings instead of regular ones in places
where pep8 was complaining about with error C0209. That part is
cherry-picked from commit [1] in master branch.

This patch also removes lower-constraints job as we agreed some time ago
to not run that job in the stable branches.

Finally it also removes functional and tempest jobs which runs OVS and
OVN from master/main branches. We don't need to test that in the stable
release. Those jobs should be run in the master branch and in stable
branches are not needed anymore.

[1] https://review.opendev.org/c/openstack/ovn-octavia-provider/+/816829

Change-Id: Id7d8422f07475aee58c2f283da67cc5e171f889b