Fix lower-constanints and pep8 jobs
This patch switches using f-strings instead of regular ones in places
where pep8 was complaining about with error C0209.

It also updates some of the lower-constraints to align them with
Neutron's lower-constraints and to make ci job happy.

It also changes OVN_BRANCH from "master" to "main" as that was renamed
in the OVN repo some time ago.

Change-Id: I8c805504e8a9e06dcdd4b1ac850d54400ef05b40