Fix python 3.9 unit test failures
Running the python 3.9 unit tests locally results in failures
like:

  TypeError: cannot pickle '_thread.RLock' object

Because we are inheriting some of the neutron code, and this
is fixed in that repository, just bump the minimum requirement
to 18.0.0 (Wallaby) now that it is released. This does not
happen in the gate since it is always using master.

Raised minimum of other libraries as necessary.

Change-Id: I820c924189d2973aefcb1452331c904f1ee7051f
Closes-bug: #1923083